name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Nx
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm install 

      - name: Run test
        run: npx nx run-many --target=test

